// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: webpage.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWebpage = `-- name: createWebpage :one
INSERT INTO webpages (id, created_at, updated_at, name, url, type)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, created_at, updated_at, name, url, type
`

type createWebpageParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Name      string
	Url       string
	Type      string
}

func (q *Queries) createWebpage(ctx context.Context, arg createWebpageParams) (Webpage, error) {
	row := q.db.QueryRowContext(ctx, createWebpage,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Name,
		arg.Url,
		arg.Type,
	)
	var i Webpage
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.Type,
	)
	return i, err
}
